log:
  config:
    # Log level: debug, info, warn, error, fatal.
    level: "info"
    # Log format, one of json, text, console.
    format: "text"
    # Enable automatic timestamps in log output, if not set, it will be defaulted to true.
    disable-timestamp: true
    # Enable annotating logs with the full stack error message, if not set, it will be defaulted to false.
    development: false
    # Stops annotating logs with the calling function's file
    disable-caller: false
    # Stacktraces are captured for WarnLevel and above logs in development and ErrorLevel and above in production.
    disable-stacktrace: false
    # stops annotating logs with the full verbose error message
    disable-error-verbose: false
  file:
    # Log file name.
    filename: "config"
    # Max log file size in MB (upper limit to 4096MB).
    max-size: 300
    # Max log file keep days. No clean up by default.
    max-days: 0
    # Maximum number of old log files to retain. No clean up by default.
    max-backups: 0
